@baseUrl = https://8080-gabrielcpai-j2projetomo-brm07dbor3y.ws-us110.gitpod.io

###
GET {{baseUrl}}/categorias

###
POST {{baseUrl}}/categorias
Content-Type: application/json

{
    "nome": "Conhecimentos Gerais"
}